name: budgeting
description: Budgeting feature for Expense Tracker.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  core:
    path: ../../core/core
  design_system:
    path: ../../core/design_system
  transactions:
    path: ../transactions
  api_client:
    path: ../../core/api_client
  local_storage:
    path: ../../core/local_storage
  auth:
    path: ../auth
  dio: ^5.8.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.2
  get_it: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.4.6
